In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('C:\\Users\\kumar\\Desktop\\train1.csv')

In [4]:
df.head(10)

,log_price,property_type,room_type,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,city,first_review,...,instant_bookable,last_review,latitude,longitude,neighbourhood,number_of_reviews,review_scores_rating,zipcode,bedrooms,beds
0,5.010635,Apartment,Entire home/apt,3,1.0,Real Bed,strict,True,NYC,18-06-16,...,f,18-07-16,40.696524,-73.991617,Brooklyn Heights,2,100.0,11201,1.0,1.0
1,5.129899,Apartment,Entire home/apt,7,1.0,Real Bed,strict,True,NYC,05-08-17,...,t,23-09-17,40.766115,-73.989040,Hell's Kitchen,6,93.0,10019,3.0,3.0
2,4.976734,Apartment,Entire home/apt,5,1.0,Real Bed,moderate,True,NYC,30-04-17,...,t,14-09-17,40.808110,-73.943756,Harlem,10,92.0,10027,1.0,3.0
3,6.620073,House,Entire home/apt,4,1.0,Real Bed,flexible,True,SF,NaN,...,f,NaN,37.772004,-122.431619,Lower Haight,0,NaN,94117,2.0,2.0
4,4.744932,Apartment,Entire home/apt,2,1.0,Real Bed,moderate,True,DC,12-05-15,...,t,22-01-17,38.925627,-77.034596,Columbia Heights,4,40.0,20009,0.0,1.0
5,4.442651,Apartment,Private room,2,1.0,Real Bed,strict,True,SF,27-08-17,...,t,05-09-17,37.753164,-122.429526,Noe Valley,3,100.0,94131,1.0,1.0
6,4.418841,Apartment,Entire home/apt,3,1.0,Real Bed,moderate,True,LA,10-03-17,...,t,21-04-17,33.980454,-118.462821,NaN,15,97.0,90292,1.0,1.0
7,4.787492,Condominium,Entire home/apt,2,1.0,Real Bed,moderate,True,LA,16-12-16,...,f,12-04-17,34.046737,-118.260439,Downtown,9,93.0,90015,1.0,1.0
8,4.787492,House,Private room,2,1.0,Real Bed,moderate,True,SF,13-02-16,...,f,24-09-17,37.781128,-122.501095,Richmond District,159,99.0,94121,1.0,1.0
9,3.583519,House,Private room,2,1.0,Real Bed,moderate,True,LA,03-04-17,...,t,16-04-17,33.992563,-117.895997,NaN,2,90.0,91748,1.0,1.0

In [15]:
X, y = make_blobs(n_samples=10, centers=3, n_features=5

SyntaxError: unexpected EOF while parsing (<ipython-input-15-a749ad426225>, line 1)

In [7]:
plt.scatter(x[:,0], x[:,1], s=5, alpha=.5)

NameError: name 'plt' is not defined

In [20]:
from sklearn.datasets import load_iris
iris = load_iris()
data = iris.data

In [ ]:
data.head(10)